language: c++

os:
    - linux
      #    - osx

compiler:
    - gcc
      #    - clang

#matrix:
#    exclude:
#        - os: osx
#          compiler: gcc
#        - os: linux
#          compiler: clang


# Install dependencies
before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa;
        sudo apt-get update -qq;
        sudo apt-get install qtbase5-dev;
        sudo apt-get install qt5-default qttools5-dev-tools;
      else
        brew update;
        brew install qt5;
        brew linkapps qt5;
        brew link --force qt5;
      fi

script:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
        ./build_linux.sh;
      else
        ./build_osx.sh;
      fi
