version: 0.1.0.{build}

# See https://github.com/vlc-qt/examples/blob/master/.appveyor.yml for examples
# This could be simplified, but I'm keeping it in case I want to add a VS build
environment:
  matrix:
  - example: presi-aoke
    name: win32
    platform: mingw
    qt: mingw492_32

install:
  - cinst nsis

init:
  - set PATH=C:\Qt\5.5\%qt%\bin;%PATH%
  - set makefiles="MinGW Makefiles"

build_script:
  - set PATH=C:\Qt\5.5\%qt%\bin;C:\Qt\Tools\mingw492_32\bin
  - build_win32.bat

artifacts:
  - path: presi-aoke-*.exe
